let games = [
  { id: "1", title: "Zelda, Tears of the Kingdom", platform: ["Switch"] },
  { id: "2", title: "Final Fantasy 7 Remake", platform: ["PS5", "Xbox"] },
  { id: "3", title: "Elden Ring", platform: ["PS5", "Xbox", "PC"] },
  { id: "4", title: "Mario Kart", platform: ["Switch"] },
  { id: "5", title: "Pokemon Scarlet", platform: ["PS5", "Xbox", "PC"] },
  { id: "6", title: "Halo Infinite", platform: ["Xbox", "PC"] },
  { id: "7", title: "God of War", platform: ["PS5"] },
  { id: "8", title: "Ratchet and Clank", platform: ["PS5"] },
  { id: "9", title: "Spiderman", platform: ["PS5"] },
  { id: "10", title: "Horizon Zero Dawn", platform: ["PS5"] },
  { id: "11", title: "The Last of Us", platform: ["PS5"] },
  { id: "12", title: "Uncharted", platform: ["PS5"] },
  { id: "13", title: "Demon Souls", platform: ["PS5"] },
  { id: "14", title: "Bloodborne", platform: ["PS5"] },
  { id: "15", title: "Sekiro", platform: ["PS5"] },
  { id: "16", title: "Dark Souls", platform: ["PS5"] },
  { id: "17", title: "Elden Ring", platform: ["PS5"] },
  { id: "18", title: "Zelda, Breath of the Wild", platform: ["Switch"] },
  { id: "19", title: "Mario Odyssey", platform: ["Switch"] },
  { id: "20", title: "Smash Bros", platform: ["Switch"] },
  { id: "21", title: "Splatoon", platform: ["Switch"] },
  { id: "22", title: "Metroid", platform: ["Switch"] },
  { id: "23", title: "Donkey Kong", platform: ["Switch"] },
  { id: "24", title: "Kirby", platform: ["Switch"] },
  { id: "25", title: "Yoshi", platform: ["Switch"] },
  { id: "26", title: "Pikmin", platform: ["Switch"] },
  { id: "27", title: "Animal Crossing", platform: ["Switch"] },
  { id: "28", title: "Luigi's Mansion", platform: ["Switch"] },
  { id: "29", title: "Star Fox", platform: ["Switch"] },
];

let authors = [
  { id: "1", name: "mario", verified: true },
  { id: "2", name: "yoshi", verified: false },
  { id: "3", name: "peach", verified: true },
  { id: "4", name: "toad", verified: false },
  { id: "5", name: "luigi", verified: true },
  { id: "6", name: "bowser", verified: false },
  { id: "7", name: "donkey kong ", verified: true },
];

let reviews = [
  { id: "1", rating: 9, content: "lorem ipsum", author_id: "1", game_id: "2" },
  { id: "2", rating: 10, content: "lorem ipsum", author_id: "2", game_id: "1" },
  { id: "3", rating: 7, content: "lorem ipsum", author_id: "3", game_id: "3" },
  { id: "4", rating: 5, content: "lorem ipsum", author_id: "2", game_id: "4" },
  { id: "5", rating: 8, content: "lorem ipsum", author_id: "2", game_id: "5" },
  { id: "6", rating: 7, content: "lorem ipsum", author_id: "1", game_id: "2" },
  { id: "7", rating: 10, content: "lorem ipsum", author_id: "3", game_id: "1" },
  { id: "8", rating: 6, content: "lorem ipsum", author_id: "4", game_id: "3" },
  { id: "21", rating: 7, content: "lorem ipsum", author_id: "2", game_id: "2" },
  {
    id: "22",
    rating: 10,
    content: "lorem ipsum",
    author_id: "3",
    game_id: "1",
  },
  { id: "23", rating: 6, content: "lorem ipsum", author_id: "4", game_id: "3" },
  { id: "24", rating: 7, content: "lorem ipsum", author_id: "2", game_id: "4" },
  { id: "25", rating: 8, content: "lorem ipsum", author_id: "2", game_id: "5" },
  { id: "26", rating: 7, content: "lorem ipsum", author_id: "1", game_id: "2" },
  {
    id: "27",
    rating: 10,
    content: "lorem ipsum",
    author_id: "3",
    game_id: "1",
  },
  { id: "28", rating: 6, content: "lorem ipsum", author_id: "4", game_id: "3" },
  { id: "29", rating: 7, content: "lorem ipsum", author_id: "2", game_id: "4" },
  { id: "30", rating: 8, content: "lorem ipsum", author_id: "2", game_id: "5" },
  { id: "31", rating: 7, content: "lorem ipsum", author_id: "1", game_id: "2" },
  {
    id: "32",
    rating: 10,
    content: "lorem ipsum",
    author_id: "3",
    game_id: "1",
  },
  { id: "33", rating: 6, content: "lorem ipsum", author_id: "4", game_id: "3" },
  { id: "34", rating: 7, content: "lorem ipsum", author_id: "2", game_id: "4" },
  { id: "35", rating: 8, content: "lorem ipsum", author_id: "2", game_id: "5" },
  { id: "36", rating: 7, content: "lorem ipsum", author_id: "1", game_id: "2" },
];

export default { games, authors, reviews };
